### ISSUE TITLE
K8s deployment ressource and job ressource make matching phase crash

### ISSUE THREAD

**Issue by Loic-R** [ystia/yorc-a4c-plugin#114]
# Bug Report

## Description
Plugin version : 3.2.0-M3
Having K8's JOB and K8's deployment on demand ressources makes matching phase crashing and return an error 500
A workaround is deleting job ressource and keep only deployment one

## Expected behavior
Having K8's JOB **AND** K8's deployment on demand ressources should not return errors at matching step

## Actual behavior
Having the both return error

## Steps to reproduce the issue

1. Upload yorc plugin
2. Configure k8s location with Container, Job, Deployment, and Service
3. Upload or create a k8's app. You can use simpleApache for example
4. Click on "matching" button

## Output of `yorc version`
Yorc Server v3.2.0-M3
Database schema version: 1.0.0
Revision: "34e008d0db595b0e5756afbe5b2d87f39eb4bcb4"

## Priority

Medium

**Comment by stebenoist** [comment]
Seems to occur at kubernetes-modifier initialization.
Here is the end of the stacktrace

2019-03-25 15:12:47 WARN  RestTechnicalExceptionHandler:348 - Uncategorized error
java.lang.NullPointerException: null
	at alien4cloud.tosca.context.ToscaContext$Context.addDependency(ToscaContext.java:161) ~[alien4cloud-tosca-2.1.1.jar!/:?]
	at alien4cloud.tosca.context.ToscaContext$Context.updateDependency(ToscaContext.java:211) ~[alien4cloud-tosca-2.1.1.jar!/:?]
	at alien4cloud.tosca.context.ToscaContext$Context.resetDependencies(ToscaContext.java:143) ~[alien4cloud-tosca-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.PolicyMatchingReplaceModifier.init(PolicyMatchingReplaceModifier.java:46) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.AbstractMatchingReplaceModifier.process(AbstractMatchingReplaceModifier.java:53) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.PolicyMatchingReplaceModifier.process(PolicyMatchingReplaceModifier.java:56) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.AbstractComposedModifier.lambda$process$0(AbstractComposedModifier.java:28) ~[alien4cloud-core-2.1.1.jar!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_161]
	at org.alien4cloud.alm.deployment.configuration.flow.modifiers.matching.AbstractComposedModifier.process(AbstractComposedModifier.java:28) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.FlowExecutor.execute(FlowExecutor.java:220) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.FlowExecutor.executeDeploymentFlow(FlowExecutor.java:208) ~[alien4cloud-core-2.1.1.jar!/:?]
	at org.alien4cloud.alm.deployment.configuration.flow.FlowExecutor$$FastClassBySpringCGLIB$$2aa9f29c.invoke(<generated>) ~[alien4cloud-core-2.1.1.jar!/:?]

**Comment by Loic-R** [comment]
In fact it didn't happened anymore to me.
Seems to be an archive version issue in a script that configure location because when done "by hand" it doesn't happen

**Comment by loicalbertin** [comment]
Ok, lets then consider it as "User Error".
