### ISSUE TITLE
Deploy 2 applications simultaneously failed

### ISSUE THREAD

**Issue by BertrandD** [ystia/yorc-a4c-plugin#45]
# Bug Report

## Description

Concurrent deployment makes an invalid zip sended to Yorc.

## Actual behavior

I have 2 applications A and B with a long initial state to complete (for example an artifact to download from a repository http)

I deploy A, and then I deploy B before A is still in INITIAL status (in A4C, before it is sended to Yorc)

Then, the two application failed. And you get the following stack trace:

```
 [2018-08-23 15:49:23][][]YorcRestException: [title: "Internal Server Error", http status code: "500", detail: "Something went wrong: [PANIC] zip: not a valid zip file"]
org.ystia.yorc.alien4cloud.plugin.rest.YorcRestException: YorcRestException: [title: "Internal Server Error", http status code: "500", detail: "Something went wrong: [PANIC] zip: not a valid zip file"]
at org.ystia.yorc.alien4cloud.plugin.rest.YorcRestException.fromYorcError(YorcRestException.java:38)
at org.ystia.yorc.alien4cloud.plugin.rest.RestClient.sendRequest(RestClient.java:170)
at org.ystia.yorc.alien4cloud.plugin.rest.RestClient.sendTopologyToYorc(RestClient.java:235)
at org.ystia.yorc.alien4cloud.plugin.DeployTask.run(DeployTask.java:138)
at org.ystia.yorc.alien4cloud.plugin.TaskManager.nextWork(TaskManager.java:89)
at org.ystia.yorc.alien4cloud.plugin.TaskManager$WorkThread.run(TaskManager.java:141)
```

## Alien4Cloud version

2.0.0

## Output of `yorc version`

```
Yorc Server v3.1.0-M1
Revision: "7b4a65ee36cf213fea07333e94aa09ec396f2fdd"
```

## Priority

Medium

**Comment by loicalbertin** [comment]
Could you elaborate on what makes the zip invalid?

**Comment by BertrandD** [comment]
We have 2 concurrent threads editing topology.yml & topology.zip, I think there is something bad with it...
