### ISSUE TITLE
Can't connect to Yorc in secure mode

### ISSUE THREAD

**Issue by laurentganne** [ystia/yorc-a4c-plugin#81]
# Issue Type

* [X] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description

Attempting to have the Alien4Cloud Yorc plugin to connect to Yorc in secure mode by:
  * creating a keystore and trustore with required client certificate and certificate authority
  * specifying a keystore and trustore using  `javax.net.ssl.trustStore` and `javax.net.ssl.keyStore` java options at Alien4Cloud launch
  * providing an https URL in Yorc plugin configuration

the plugin fails to connect to Yorc with this error :
```
2019-01-08 16:34:10.933 WARN  [qtp1131592118-15] RestClient:131 - Unable to retrieve deployments due to: An error occurred while calling GET https://127.0.0.1:8800/deployments
2019-01-08 16:34:10.937 ERROR [qtp1131592118-15] OrchestratorController:127 - Failed to instantiate orchestrator because of invalid configuration.
alien4cloud.paas.exception.PluginConfigurationException: Failed to connect to yorc
        at org.ystia.yorc.alien4cloud.plugin.rest.RestClient.setProviderConfiguration(RestClient.java:133) ~[?:?]
        at org.ystia.yorc.alien4cloud.plugin.YorcPaaSProvider.setConfiguration(YorcPaaSProvider.java:449) ~[?:?]
        at org.ystia.yorc.alien4cloud.plugin.YorcPaaSProvider.setConfiguration(YorcPaaSProvider.java:62) 
...[Redacted]...
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://127.0.0.1:8800/deployments": Received fatal alert: bad_certificate; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate

```

Java SSL debug logs shows no certificate is found on the client during the SSL handshake:
```
*** CertificateRequest
Cert Types: RSA, ECDSA
Supported Signature Algorithms: SHA256withRSA, SHA256withECDSA, SHA384withRSA, SHA384withECDSA, SHA512withRSA, SHA512withECDSA, SHA1withRSA, SHA1withECDSA
Cert Authorities:
<CN=yorc, OU=yorc, O=ystia, L=Default City, C=FR>
qtp1131592118-15, READ: TLSv1.2 Handshake, length = 4
*** ServerHelloDone
Warning: no suitable certificate found - continuing without client authentication
*** Certificate chain
<Empty>
***
```
System settings for keystore don't seem to be used here.
While some java code using the same truststore and keystore, creating a socket from a socket factory using a system defaut SSL context, is able to perform a handshake with the secured Yorc server.

## Alien4Cloud version

2.1.0

## Output of `yorc version`

3.2.0-SNAPSHOT (develop) or 3.1.0

## Priority

Medium

* High = We should stop anything we are doing and do this. If you're writing this calmly, you should probably choose another option. If it's really that urgent, please make sure we read this.
* Medium = It's important that we do this within a few days.
* Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

**Comment by laurentganne** [comment]
Re-opening for a backport on 3.1
